### ISSUE TITLE
NETStandard.Library should this be "1.0.0-rc2-*" or "1.5.0-rc2-*" ??

### ISSUE THREAD

**Issue by StefH** [StevenLiekens/dotnet-core-appveyor#4]
Because my VS2015 complains about that 1.0.0 cannot be found ?

**Comment by sliekens** [comment]
I don't know if it should be 1.0.0 or 1.5.0 but both packages exist.

https://dotnet.myget.org/feed/dotnet-core/package/nuget/NETStandard.Library/1.0.0-rc2-23910

https://dotnet.myget.org/feed/dotnet-core/package/nuget/NETStandard.Library/1.5.0-rc2-24103

I can't really spot the difference.

**Comment by sliekens** [comment]
in RTM there is only version 1.6.0 for this package. I assume this number is 1.6.0 because the highest platform standard is 1.6 (netstandard1.6). I still don't entirely understand the platform standard versions, but anyway it should be 1.6.0 because that's all we get right now. :D
